; ESP8266 + HX711 称重传感器固件
;
; 接线:
;   HX711 DT  → D2 (GPIO4)
;   HX711 SCK → D1 (GPIO5)
;   HX711 VCC → 3.3V
;   HX711 GND → GND

[platformio]
default_envs = fw-scale-test

[env]
framework = arduino
monitor_speed = 115200
lib_deps =
    bogde/HX711@^0.7.6

; ===== 共用 build_flags =====
build_flags =
    -D FIRMWARE_CHANNEL=\"self\"

; ===== HX711 称重测试 =====
[env:fw-scale-test]
platform = espressif8266
board = nodemcuv2
build_flags =
    ${env.build_flags}
    -D DEVICE_SERIAL_PREFIX=\"SCALE-TEST-\"
